FROM node:lts

WORKDIR /app

COPY package.json .

COPY package-lock.json .

RUN npm install -g npm@latest

RUN npm install -g react-scripts

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]